#!/usr/bin/env bash

# Compile a C file for wasi-threads using a wasi-sdk installation.
#
# Usage: cc foo.c -o foo.wasm

WASI_SDK_DIR=${WASI_SDK_DIR:="/opt/wasi-sdk/wasi-sdk-20.0"}
CC="$WASI_SDK_DIR/bin/clang --sysroot $WASI_SDK_DIR/share/wasi-sysroot"
CFLAGS="--target=wasm32-wasi-threads -pthread"
LDFLAGS="-Wl,--import-memory,--export-memory,--max-memory=67108864"

if [[ ! -d "$WASI_SDK_DIR" || ! -f "$WASI_SDK_DIR/bin/clang" ]]; then
    echo "Could not find wasi-sdk installation at: $WASI_SDK_DIR"
    echo "You may need to set \`WASI_SDK_DIR=<path to installation> cc\`"
    exit 1
fi

(set -x; $CC $CFLAGS $LDFLAGS $@)
