#!/usr/bin/env python

import os

exe = os.environ['EXE']
delay = '0.01'
script_dir = os.path.dirname(os.path.realpath(__file__))
statistics_script = script_dir + os.path.sep + 'statistics'


def run(cmd):
    os.system(cmd)


print()
print('Calculate the time (in microseconds) to spawn the first thread in a new process.')
print(f'> {exe} 1')
file = 'first-thread.txt'
run(f'rm -f {file}')
for _ in range(0, 100):
    run(f'sleep {delay}')
    run(f'{exe} 1 >> {file}')
run(f'cat {file} | {statistics_script}')

print()
print('Calculate the time (in microseconds) to spawn each of the first 10 threads; this creates 10 distinct processes to get 100 samples.')
print(f'> {exe} 10')
file = 'first-10-threads.txt'
run(f'rm -f {file}')
for _ in range(0, 10):
    run(f'sleep {delay}')
    run(f'{exe} 10 >> {file}')
run(f'cat {file} | {statistics_script}')

print()
print('Calculate the time (in microseconds) for each of 100 threads in a single process.')
print(f'> {exe} 100')
file = 'all-100-threads.txt'
run(f'rm -f {file}')
run(f'{exe} 100 >> {file}')
run(f'cat {file} | {statistics_script}')

print()
print('Calculate the time (in microseconds) to spawn each of 1000 threads in a single process.')
print(f'> {exe} 1000')
file = 'all-1000-threads.txt'
run(f'rm -f {file}')
run(f'{exe} 1000 >> {file}')
run(f'cat {file} | {statistics_script}')

print()
print('Calculate the time (in microseconds) to spawn each of the last 10 threads of 100 threads spawned in a single process.')
print(f'> {exe} 100 | tail')
file = 'last-10-threads-of-100.txt'
run(f'rm -f {file}')
run(f'{exe} 100 | tail >> {file}')
run(f'cat {file} | {statistics_script}')

print()
print('Calculate the time (in microseconds) to spawn each of the last 10 threads of 1000 threads spawned in a single process.')
print(f'> {exe} 1000 | tail')
file = 'last-10-threads-of-1000.txt'
run(f'rm -f {file}')
run(f'{exe} 1000 | tail >> {file}')
run(f'cat {file} | {statistics_script}')
