#!/usr/bin/env python

import sys
import statistics

numbers = list(map(int, sys.stdin.readlines()))
# print('numbers: {}'.format(numbers))
print('min: {}'.format(min(numbers)))
print('mean: {}'.format(statistics.mean(numbers)))
print('max: {}'.format(max(numbers)))
print('quantiles: {}'.format(statistics.quantiles(numbers)))
